---

  - name: check if cargo is installed
    ansible.builtin.shell: 
      cmd: command -v cargo
    register: cargo_exists
    ignore_errors: yes
    tags: rust
  
  - name: Download Installer
    when: cargo_exists is failed
    ansible.builtin.get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust

  - name: install rust/cargo
    when: cargo_exists is failed
    ansible.builtin.shell: 
      cmd: /tmp/sh.rustup.rs -y
    tags:
      - rust
  
  - name: Download Helix editor
    ansible.builtin.git:
      repo: 'https://github.com/helix-editor/helix'
      dest: "/tmp/helix"
    tags: rust

  - name: Install Helix editor
    ansible.builtin.shell: 
      cmd: cargo install --path /tmp/helix/helix-term
    tags: rust

  - name: Copy Helix Runtime
    ansible.builtin.copy:
      src: /tmp/helix/runtime
      dest: ~/.config/helix
    tags: rust
