---
  
  - name: Add Docker GPG key
    ansible.builtin.get_url:
      url: "{{ docker_gpg_url }}"
      dest: /etc/apt/trusted.gpg.d/docker.asc
      mode: "0644"
      force: yes
    become: yes
    tags: docker

  - name: Add Docker repository
    ansible.builtin.apt_repository:
      repo: "{{ docker_repo }}"
    become: yes
    tags: docker

  - name: Install Docker
    ansible.builtin.apt:
      name: docker-ce
      state: latest
      update_cache: yes
    become: yes
    tags: docker

  - name: Install Docker Compose
    ansible.builtin.get_url:
      url: "{{ docker_compose_url }}"
      dest: /usr/local/bin/docker-compose
      mode: u+x,g+x,o+x
    tags: docker
      
  - name: Add user '{{ ansible_user_id }}' to Docker group
    ansible.builtin.user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes
    tags: docker