---

- hosts: localhost

  vars_files: 
  - docker/vars.yml
  - shell/vars.yml

  tasks:
  - name: Setup Docker
    ansible.builtin.include_tasks: docker/tasks.yml
    tags: docker
    
  - name: Install Git
    ansible.builtin.apt: 
      name: git
      update_cache: yes
    become: yes
    tags: git
  
  - name: Install Tmux
    ansible.builtin.apt:
      name: tmux
      update_cache: yes
    become: yes
    tags: tmux
  
  - name: Setup Shell
    ansible.builtin.include_tasks: shell/tasks.yml
    tags: shell

  - name: Install Rust
    ansible.builtin.include_tasks: rust/tasks.yml
    tags: rust